# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63076a66657c50665e3bd231f879d50ab0f03915c4b294fbd0b18f96c4430d364ae97bf0ca80f9130ccda461d8bf4605d3e910d612e81243d21f9ee6a21fd36b

test:
  secret_key_base: 015c80955678ecdeb82a76ad62e97e4c3516d1b88bed66404fb63b36dbd8ff091a797f9151bf27c52874211936b09997313ffe81456748025b2ca271965db36c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
